[build]
builder = "nixpacks"
nixpacks.providers = ["python"]

[deploy]
startCommand = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[[services]]
name = "xeno-transaction-validator-api"
runtime = "python"

[environments.production]
PORT = 8000
PYTHONUNBUFFERED = "true"
